'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace LosSaboresDelAbuelo

    Partial Public Class cliente
        Public Property IdCliente As Integer
        Public Property NombreCliente As String
    
        Public Overridable Property pedido As ICollection(Of pedido) = New HashSet(Of pedido)
    
    End Class

End Namespace
