'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace LosSaboresDelAbuelo

    Partial Public Class pedido
        Public Property IdPedido As Long
        Public Property NOrden As String
        Public Property IdCliente As Integer
        Public Property MetodoPago As String
        Public Property Total As Decimal
    
        Public Overridable Property cliente As cliente
        Public Overridable Property pedidoDetalle As ICollection(Of pedidoDetalle) = New HashSet(Of pedidoDetalle)
    
    End Class

End Namespace
