'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace LosSaboresDelAbuelo

    Partial Public Class pedidoDetalle
        Public Property IdProductoPedido As Long
        Public Property IdPedido As Long
        Public Property IdProducto As Integer
        Public Property Cantidad As Decimal
    
        Public Overridable Property pedido As pedido
        Public Overridable Property producto As producto
    
    End Class

End Namespace
